-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity softmax_latency_ap_fixed_ap_fixed_softmax_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of softmax_latency_ap_fixed_ap_fixed_softmax_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exp_table1_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce0 : STD_LOGIC;
    signal exp_table1_q0 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce1 : STD_LOGIC;
    signal exp_table1_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce2 : STD_LOGIC;
    signal exp_table1_q2 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce3 : STD_LOGIC;
    signal exp_table1_q3 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce4 : STD_LOGIC;
    signal exp_table1_q4 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address5 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce5 : STD_LOGIC;
    signal exp_table1_q5 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address6 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce6 : STD_LOGIC;
    signal exp_table1_q6 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address7 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce7 : STD_LOGIC;
    signal exp_table1_q7 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address8 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce8 : STD_LOGIC;
    signal exp_table1_q8 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_table1_address9 : STD_LOGIC_VECTOR (9 downto 0);
    signal exp_table1_ce9 : STD_LOGIC;
    signal exp_table1_q9 : STD_LOGIC_VECTOR (17 downto 0);
    signal invert_table2_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal invert_table2_ce0 : STD_LOGIC;
    signal invert_table2_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal exp_res_0_V_reg_775 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_1_V_reg_780 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_2_V_reg_785 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_3_V_reg_790 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_4_V_reg_795 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_5_V_reg_800 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_6_V_reg_805 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_7_V_reg_810 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_8_V_reg_815 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_res_9_V_reg_820 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln251_fu_262_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_1_fu_277_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_2_fu_292_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_3_fu_307_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_4_fu_322_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_5_fu_337_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_6_fu_352_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_7_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_8_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln251_9_fu_397_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln259_fu_466_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_V_fu_252_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_1_fu_267_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_2_fu_282_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_3_fu_297_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_4_fu_312_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_5_fu_327_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_6_fu_342_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_7_fu_357_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_8_fu_372_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_V_9_fu_387_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln703_fu_402_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_fu_402_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_1_fu_408_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_1_fu_408_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_1_fu_408_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_2_fu_414_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_2_fu_414_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_fu_402_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_4_fu_426_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_4_fu_426_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_5_fu_432_p0 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_5_fu_432_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_5_fu_432_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_6_fu_438_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_6_fu_438_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_4_fu_426_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_7_fu_444_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln703_3_fu_420_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal exp_sum_V_fu_450_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal y_V_10_fu_456_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln1118_fu_655_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_1_fu_662_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_2_fu_669_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_3_fu_676_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_4_fu_683_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_5_fu_690_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_6_fu_697_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_7_fu_704_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_8_fu_711_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_9_fu_718_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_fu_655_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln1116_fu_471_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln1118_1_fu_662_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_2_fu_669_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_3_fu_676_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_4_fu_683_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_5_fu_690_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_6_fu_697_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_7_fu_704_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_8_fu_711_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal mul_ln1118_9_fu_718_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to1 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component myproject_mul_mul_14s_18s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component softmax_latency_ap_fixed_ap_fixed_softmax_config5_s_exp_tbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address5 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address6 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address7 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address8 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce8 : IN STD_LOGIC;
        q8 : OUT STD_LOGIC_VECTOR (17 downto 0);
        address9 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce9 : IN STD_LOGIC;
        q9 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component softmax_latency_ap_fixed_ap_fixed_softmax_config5_s_invercud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;



begin
    exp_table1_U : component softmax_latency_ap_fixed_ap_fixed_softmax_config5_s_exp_tbkb
    generic map (
        DataWidth => 18,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => exp_table1_address0,
        ce0 => exp_table1_ce0,
        q0 => exp_table1_q0,
        address1 => exp_table1_address1,
        ce1 => exp_table1_ce1,
        q1 => exp_table1_q1,
        address2 => exp_table1_address2,
        ce2 => exp_table1_ce2,
        q2 => exp_table1_q2,
        address3 => exp_table1_address3,
        ce3 => exp_table1_ce3,
        q3 => exp_table1_q3,
        address4 => exp_table1_address4,
        ce4 => exp_table1_ce4,
        q4 => exp_table1_q4,
        address5 => exp_table1_address5,
        ce5 => exp_table1_ce5,
        q5 => exp_table1_q5,
        address6 => exp_table1_address6,
        ce6 => exp_table1_ce6,
        q6 => exp_table1_q6,
        address7 => exp_table1_address7,
        ce7 => exp_table1_ce7,
        q7 => exp_table1_q7,
        address8 => exp_table1_address8,
        ce8 => exp_table1_ce8,
        q8 => exp_table1_q8,
        address9 => exp_table1_address9,
        ce9 => exp_table1_ce9,
        q9 => exp_table1_q9);

    invert_table2_U : component softmax_latency_ap_fixed_ap_fixed_softmax_config5_s_invercud
    generic map (
        DataWidth => 14,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => invert_table2_address0,
        ce0 => invert_table2_ce0,
        q0 => invert_table2_q0);

    myproject_mul_mul_14s_18s_26_1_1_U1260 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_fu_655_p0,
        din1 => exp_res_0_V_reg_775,
        dout => mul_ln1118_fu_655_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1261 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_1_fu_662_p0,
        din1 => exp_res_1_V_reg_780,
        dout => mul_ln1118_1_fu_662_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1262 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_2_fu_669_p0,
        din1 => exp_res_2_V_reg_785,
        dout => mul_ln1118_2_fu_669_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1263 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_3_fu_676_p0,
        din1 => exp_res_3_V_reg_790,
        dout => mul_ln1118_3_fu_676_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1264 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_4_fu_683_p0,
        din1 => exp_res_4_V_reg_795,
        dout => mul_ln1118_4_fu_683_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1265 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_5_fu_690_p0,
        din1 => exp_res_5_V_reg_800,
        dout => mul_ln1118_5_fu_690_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1266 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_6_fu_697_p0,
        din1 => exp_res_6_V_reg_805,
        dout => mul_ln1118_6_fu_697_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1267 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_7_fu_704_p0,
        din1 => exp_res_7_V_reg_810,
        dout => mul_ln1118_7_fu_704_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1268 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_8_fu_711_p0,
        din1 => exp_res_8_V_reg_815,
        dout => mul_ln1118_8_fu_711_p2);

    myproject_mul_mul_14s_18s_26_1_1_U1269 : component myproject_mul_mul_14s_18s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 18,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln1118_9_fu_718_p0,
        din1 => exp_res_9_V_reg_820,
        dout => mul_ln1118_9_fu_718_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                exp_res_0_V_reg_775 <= exp_table1_q0;
                exp_res_1_V_reg_780 <= exp_table1_q1;
                exp_res_2_V_reg_785 <= exp_table1_q2;
                exp_res_3_V_reg_790 <= exp_table1_q3;
                exp_res_4_V_reg_795 <= exp_table1_q4;
                exp_res_5_V_reg_800 <= exp_table1_q5;
                exp_res_6_V_reg_805 <= exp_table1_q6;
                exp_res_7_V_reg_810 <= exp_table1_q7;
                exp_res_8_V_reg_815 <= exp_table1_q8;
                exp_res_9_V_reg_820 <= exp_table1_q9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln703_1_fu_408_p0 <= exp_table1_q2;
    add_ln703_1_fu_408_p1 <= exp_table1_q7;
    add_ln703_1_fu_408_p2 <= std_logic_vector(signed(add_ln703_1_fu_408_p0) + signed(add_ln703_1_fu_408_p1));
    add_ln703_2_fu_414_p1 <= exp_table1_q3;
    add_ln703_2_fu_414_p2 <= std_logic_vector(unsigned(add_ln703_1_fu_408_p2) + unsigned(add_ln703_2_fu_414_p1));
    add_ln703_3_fu_420_p2 <= std_logic_vector(unsigned(add_ln703_2_fu_414_p2) + unsigned(add_ln703_fu_402_p2));
    add_ln703_4_fu_426_p0 <= exp_table1_q6;
    add_ln703_4_fu_426_p1 <= exp_table1_q5;
    add_ln703_4_fu_426_p2 <= std_logic_vector(signed(add_ln703_4_fu_426_p0) + signed(add_ln703_4_fu_426_p1));
    add_ln703_5_fu_432_p0 <= exp_table1_q9;
    add_ln703_5_fu_432_p1 <= exp_table1_q8;
    add_ln703_5_fu_432_p2 <= std_logic_vector(signed(add_ln703_5_fu_432_p0) + signed(add_ln703_5_fu_432_p1));
    add_ln703_6_fu_438_p1 <= exp_table1_q4;
    add_ln703_6_fu_438_p2 <= std_logic_vector(unsigned(add_ln703_5_fu_432_p2) + unsigned(add_ln703_6_fu_438_p1));
    add_ln703_7_fu_444_p2 <= std_logic_vector(unsigned(add_ln703_6_fu_438_p2) + unsigned(add_ln703_4_fu_426_p2));
    add_ln703_fu_402_p0 <= exp_table1_q0;
    add_ln703_fu_402_p1 <= exp_table1_q1;
    add_ln703_fu_402_p2 <= std_logic_vector(signed(add_ln703_fu_402_p0) + signed(add_ln703_fu_402_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_ce)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = ap_ce) or ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to1 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= mul_ln1118_fu_655_p2(25 downto 10);
    ap_return_1 <= mul_ln1118_1_fu_662_p2(25 downto 10);
    ap_return_2 <= mul_ln1118_2_fu_669_p2(25 downto 10);
    ap_return_3 <= mul_ln1118_3_fu_676_p2(25 downto 10);
    ap_return_4 <= mul_ln1118_4_fu_683_p2(25 downto 10);
    ap_return_5 <= mul_ln1118_5_fu_690_p2(25 downto 10);
    ap_return_6 <= mul_ln1118_6_fu_697_p2(25 downto 10);
    ap_return_7 <= mul_ln1118_7_fu_704_p2(25 downto 10);
    ap_return_8 <= mul_ln1118_8_fu_711_p2(25 downto 10);
    ap_return_9 <= mul_ln1118_9_fu_718_p2(25 downto 10);
    exp_sum_V_fu_450_p2 <= std_logic_vector(unsigned(add_ln703_7_fu_444_p2) + unsigned(add_ln703_3_fu_420_p2));
    exp_table1_address0 <= zext_ln251_fu_262_p1(10 - 1 downto 0);
    exp_table1_address1 <= zext_ln251_1_fu_277_p1(10 - 1 downto 0);
    exp_table1_address2 <= zext_ln251_2_fu_292_p1(10 - 1 downto 0);
    exp_table1_address3 <= zext_ln251_3_fu_307_p1(10 - 1 downto 0);
    exp_table1_address4 <= zext_ln251_4_fu_322_p1(10 - 1 downto 0);
    exp_table1_address5 <= zext_ln251_5_fu_337_p1(10 - 1 downto 0);
    exp_table1_address6 <= zext_ln251_6_fu_352_p1(10 - 1 downto 0);
    exp_table1_address7 <= zext_ln251_7_fu_367_p1(10 - 1 downto 0);
    exp_table1_address8 <= zext_ln251_8_fu_382_p1(10 - 1 downto 0);
    exp_table1_address9 <= zext_ln251_9_fu_397_p1(10 - 1 downto 0);

    exp_table1_ce0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce0 <= ap_const_logic_1;
        else 
            exp_table1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce1_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce1 <= ap_const_logic_1;
        else 
            exp_table1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce2_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce2 <= ap_const_logic_1;
        else 
            exp_table1_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce3_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce3 <= ap_const_logic_1;
        else 
            exp_table1_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce4_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce4 <= ap_const_logic_1;
        else 
            exp_table1_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce5_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce5 <= ap_const_logic_1;
        else 
            exp_table1_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce6_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce6 <= ap_const_logic_1;
        else 
            exp_table1_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce7_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce7 <= ap_const_logic_1;
        else 
            exp_table1_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce8_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce8 <= ap_const_logic_1;
        else 
            exp_table1_ce8 <= ap_const_logic_0;
        end if; 
    end process;


    exp_table1_ce9_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            exp_table1_ce9 <= ap_const_logic_1;
        else 
            exp_table1_ce9 <= ap_const_logic_0;
        end if; 
    end process;

    invert_table2_address0 <= zext_ln259_fu_466_p1(10 - 1 downto 0);

    invert_table2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_logic_1 = ap_ce) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            invert_table2_ce0 <= ap_const_logic_1;
        else 
            invert_table2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln1118_1_fu_662_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_2_fu_669_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_3_fu_676_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_4_fu_683_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_5_fu_690_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_6_fu_697_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_7_fu_704_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_8_fu_711_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_9_fu_718_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
    mul_ln1118_fu_655_p0 <= sext_ln1116_fu_471_p1(14 - 1 downto 0);
        sext_ln1116_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(invert_table2_q0),26));

    y_V_10_fu_456_p4 <= exp_sum_V_fu_450_p2(17 downto 8);
    y_V_1_fu_267_p4 <= data_1_V_read(15 downto 6);
    y_V_2_fu_282_p4 <= data_2_V_read(15 downto 6);
    y_V_3_fu_297_p4 <= data_3_V_read(15 downto 6);
    y_V_4_fu_312_p4 <= data_4_V_read(15 downto 6);
    y_V_5_fu_327_p4 <= data_5_V_read(15 downto 6);
    y_V_6_fu_342_p4 <= data_6_V_read(15 downto 6);
    y_V_7_fu_357_p4 <= data_7_V_read(15 downto 6);
    y_V_8_fu_372_p4 <= data_8_V_read(15 downto 6);
    y_V_9_fu_387_p4 <= data_9_V_read(15 downto 6);
    y_V_fu_252_p4 <= data_0_V_read(15 downto 6);
    zext_ln251_1_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_1_fu_267_p4),64));
    zext_ln251_2_fu_292_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_2_fu_282_p4),64));
    zext_ln251_3_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_3_fu_297_p4),64));
    zext_ln251_4_fu_322_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_4_fu_312_p4),64));
    zext_ln251_5_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_5_fu_327_p4),64));
    zext_ln251_6_fu_352_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_6_fu_342_p4),64));
    zext_ln251_7_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_7_fu_357_p4),64));
    zext_ln251_8_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_8_fu_372_p4),64));
    zext_ln251_9_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_9_fu_387_p4),64));
    zext_ln251_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_fu_252_p4),64));
    zext_ln259_fu_466_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_V_10_fu_456_p4),64));
end behav;
