// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_resource_ap_fixed_ap_fixed_config2_mult_s_HH_
#define _dense_resource_ap_fixed_ap_fixed_config2_mult_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "myproject_mul_mul_16s_9s_25_1_1.h"
#include "myproject_mul_mul_16s_10s_26_1_1.h"
#include "myproject_mul_mul_16s_7ns_23_1_1.h"
#include "myproject_mul_mul_16s_8s_24_1_1.h"
#include "myproject_mul_mul_16s_10ns_26_1_1.h"
#include "myproject_mul_mul_16s_9ns_25_1_1.h"
#include "myproject_mul_mul_16s_8ns_24_1_1.h"

namespace ap_rtl {

struct dense_resource_ap_fixed_ap_fixed_config2_mult_s : public sc_module {
    // Port declarations 14
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<16> > data_0_V_read;
    sc_in< sc_lv<16> > data_1_V_read;
    sc_in< sc_lv<16> > data_2_V_read;
    sc_in< sc_lv<16> > data_3_V_read;
    sc_in< sc_lv<16> > data_4_V_read;
    sc_in< sc_lv<16> > data_5_V_read;
    sc_in< sc_lv<16> > data_6_V_read;
    sc_in< sc_lv<16> > data_7_V_read;
    sc_in< sc_lv<16> > data_8_V_read;
    sc_out< sc_lv<16> > ap_return_0;
    sc_out< sc_lv<16> > ap_return_1;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    dense_resource_ap_fixed_ap_fixed_config2_mult_s(sc_module_name name);
    SC_HAS_PROCESS(dense_resource_ap_fixed_ap_fixed_config2_mult_s);

    ~dense_resource_ap_fixed_ap_fixed_config2_mult_s();

    sc_trace_file* mVcdFile;

    myproject_mul_mul_16s_9s_25_1_1<1,1,16,9,25>* myproject_mul_mul_16s_9s_25_1_1_U4;
    myproject_mul_mul_16s_10s_26_1_1<1,1,16,10,26>* myproject_mul_mul_16s_10s_26_1_1_U5;
    myproject_mul_mul_16s_7ns_23_1_1<1,1,16,7,23>* myproject_mul_mul_16s_7ns_23_1_1_U6;
    myproject_mul_mul_16s_8s_24_1_1<1,1,16,8,24>* myproject_mul_mul_16s_8s_24_1_1_U7;
    myproject_mul_mul_16s_10ns_26_1_1<1,1,16,10,26>* myproject_mul_mul_16s_10ns_26_1_1_U8;
    myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>* myproject_mul_mul_16s_9ns_25_1_1_U9;
    myproject_mul_mul_16s_10s_26_1_1<1,1,16,10,26>* myproject_mul_mul_16s_10s_26_1_1_U10;
    myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>* myproject_mul_mul_16s_9ns_25_1_1_U11;
    myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>* myproject_mul_mul_16s_9ns_25_1_1_U12;
    myproject_mul_mul_16s_8ns_24_1_1<1,1,16,8,24>* myproject_mul_mul_16s_8ns_24_1_1_U13;
    myproject_mul_mul_16s_9s_25_1_1<1,1,16,9,25>* myproject_mul_mul_16s_9s_25_1_1_U14;
    myproject_mul_mul_16s_8s_24_1_1<1,1,16,8,24>* myproject_mul_mul_16s_8s_24_1_1_U15;
    myproject_mul_mul_16s_8ns_24_1_1<1,1,16,8,24>* myproject_mul_mul_16s_8ns_24_1_1_U16;
    myproject_mul_mul_16s_10ns_26_1_1<1,1,16,10,26>* myproject_mul_mul_16s_10ns_26_1_1_U17;
    myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>* myproject_mul_mul_16s_9ns_25_1_1_U18;
    sc_signal< sc_lv<15> > trunc_ln_reg_730;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<16> > trunc_ln708_1_reg_735;
    sc_signal< sc_lv<15> > add_ln703_1286_fu_398_p2;
    sc_signal< sc_lv<15> > add_ln703_1286_reg_740;
    sc_signal< sc_lv<16> > add_ln703_1288_fu_404_p2;
    sc_signal< sc_lv<16> > add_ln703_1288_reg_745;
    sc_signal< sc_lv<16> > add_ln703_1290_fu_416_p2;
    sc_signal< sc_lv<16> > add_ln703_1290_reg_750;
    sc_signal< sc_lv<16> > add_ln703_1296_fu_549_p2;
    sc_signal< sc_lv<16> > add_ln703_1296_reg_755;
    sc_signal< sc_lv<15> > add_ln703_1297_fu_555_p2;
    sc_signal< sc_lv<15> > add_ln703_1297_reg_760;
    sc_signal< sc_lv<16> > add_ln703_1299_fu_567_p2;
    sc_signal< sc_lv<16> > add_ln703_1299_reg_765;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<25> > mul_ln1118_fu_625_p2;
    sc_signal< sc_lv<26> > mul_ln1118_981_fu_632_p2;
    sc_signal< sc_lv<16> > shl_ln_fu_188_p1;
    sc_signal< sc_lv<21> > shl_ln_fu_188_p3;
    sc_signal< sc_lv<16> > shl_ln1118_s_fu_200_p1;
    sc_signal< sc_lv<17> > shl_ln1118_s_fu_200_p3;
    sc_signal< sc_lv<22> > sext_ln1118_854_fu_196_p1;
    sc_signal< sc_lv<22> > sext_ln1118_855_fu_208_p1;
    sc_signal< sc_lv<22> > add_ln1118_fu_212_p2;
    sc_signal< sc_lv<12> > tmp_497_fu_218_p4;
    sc_signal< sc_lv<23> > mul_ln1118_982_fu_639_p2;
    sc_signal< sc_lv<13> > tmp_498_fu_240_p4;
    sc_signal< sc_lv<24> > mul_ln1118_983_fu_646_p2;
    sc_signal< sc_lv<14> > tmp_499_fu_261_p4;
    sc_signal< sc_lv<26> > mul_ln1118_984_fu_653_p2;
    sc_signal< sc_lv<16> > sext_ln1118_863_fu_295_p0;
    sc_signal< sc_lv<16> > tmp_fu_299_p1;
    sc_signal< sc_lv<19> > tmp_fu_299_p3;
    sc_signal< sc_lv<20> > sext_ln1118_863_fu_295_p1;
    sc_signal< sc_lv<20> > sext_ln1118_868_fu_307_p1;
    sc_signal< sc_lv<20> > sub_ln1118_268_fu_311_p2;
    sc_signal< sc_lv<10> > trunc_ln708_s_fu_317_p4;
    sc_signal< sc_lv<16> > shl_ln1118_348_fu_335_p1;
    sc_signal< sc_lv<25> > shl_ln1118_348_fu_335_p3;
    sc_signal< sc_lv<16> > shl_ln1118_349_fu_347_p1;
    sc_signal< sc_lv<21> > shl_ln1118_349_fu_347_p3;
    sc_signal< sc_lv<26> > sext_ln1118_865_fu_343_p1;
    sc_signal< sc_lv<26> > sext_ln1118_866_fu_355_p1;
    sc_signal< sc_lv<26> > sub_ln1118_fu_359_p2;
    sc_signal< sc_lv<25> > mul_ln1118_985_fu_660_p2;
    sc_signal< sc_lv<15> > trunc_ln708_793_fu_379_p4;
    sc_signal< sc_lv<15> > sext_ln216_45_fu_270_p1;
    sc_signal< sc_lv<15> > sext_ln216_44_fu_249_p1;
    sc_signal< sc_lv<15> > sext_ln216_fu_228_p1;
    sc_signal< sc_lv<15> > add_ln703_1285_fu_392_p2;
    sc_signal< sc_lv<16> > sext_ln708_782_fu_327_p1;
    sc_signal< sc_lv<16> > trunc_ln708_5_fu_282_p4;
    sc_signal< sc_lv<16> > sext_ln708_783_fu_388_p1;
    sc_signal< sc_lv<16> > trunc_ln708_7_fu_365_p4;
    sc_signal< sc_lv<16> > add_ln703_1289_fu_410_p2;
    sc_signal< sc_lv<26> > mul_ln1118_986_fu_667_p2;
    sc_signal< sc_lv<25> > mul_ln1118_987_fu_674_p2;
    sc_signal< sc_lv<15> > trunc_ln708_794_fu_431_p4;
    sc_signal< sc_lv<25> > mul_ln1118_988_fu_681_p2;
    sc_signal< sc_lv<15> > trunc_ln708_795_fu_444_p4;
    sc_signal< sc_lv<24> > mul_ln1118_989_fu_688_p2;
    sc_signal< sc_lv<14> > trunc_ln708_796_fu_457_p4;
    sc_signal< sc_lv<25> > mul_ln1118_990_fu_695_p2;
    sc_signal< sc_lv<15> > trunc_ln708_797_fu_470_p4;
    sc_signal< sc_lv<24> > mul_ln1118_991_fu_702_p2;
    sc_signal< sc_lv<14> > tmp_500_fu_483_p4;
    sc_signal< sc_lv<24> > mul_ln1118_992_fu_709_p2;
    sc_signal< sc_lv<14> > tmp_501_fu_496_p4;
    sc_signal< sc_lv<26> > mul_ln1118_993_fu_716_p2;
    sc_signal< sc_lv<25> > mul_ln1118_994_fu_723_p2;
    sc_signal< sc_lv<15> > trunc_ln708_798_fu_518_p4;
    sc_signal< sc_lv<16> > sext_ln708_784_fu_440_p1;
    sc_signal< sc_lv<16> > trunc_ln708_9_fu_422_p4;
    sc_signal< sc_lv<16> > sext_ln708_787_fu_479_p1;
    sc_signal< sc_lv<16> > sext_ln708_786_fu_466_p1;
    sc_signal< sc_lv<16> > sext_ln708_785_fu_453_p1;
    sc_signal< sc_lv<16> > add_ln703_1294_fu_537_p2;
    sc_signal< sc_lv<16> > add_ln703_1293_fu_531_p2;
    sc_signal< sc_lv<16> > add_ln703_1295_fu_543_p2;
    sc_signal< sc_lv<15> > sext_ln216_47_fu_505_p1;
    sc_signal< sc_lv<15> > sext_ln216_46_fu_492_p1;
    sc_signal< sc_lv<16> > sext_ln708_788_fu_527_p1;
    sc_signal< sc_lv<16> > trunc_ln708_16_fu_509_p4;
    sc_signal< sc_lv<16> > add_ln703_1298_fu_561_p2;
    sc_signal< sc_lv<16> > sext_ln708_fu_573_p1;
    sc_signal< sc_lv<16> > add_ln703_fu_576_p2;
    sc_signal< sc_lv<16> > sext_ln703_fu_581_p1;
    sc_signal< sc_lv<16> > add_ln703_1287_fu_584_p2;
    sc_signal< sc_lv<16> > add_ln703_1291_fu_590_p2;
    sc_signal< sc_lv<16> > sext_ln703_257_fu_600_p1;
    sc_signal< sc_lv<16> > add_ln703_1300_fu_603_p2;
    sc_signal< sc_lv<16> > add_ln703_1292_fu_594_p2;
    sc_signal< sc_lv<16> > acc_1_V_fu_608_p2;
    sc_signal< sc_lv<9> > mul_ln1118_fu_625_p1;
    sc_signal< sc_lv<10> > mul_ln1118_981_fu_632_p1;
    sc_signal< sc_lv<7> > mul_ln1118_982_fu_639_p1;
    sc_signal< sc_lv<8> > mul_ln1118_983_fu_646_p1;
    sc_signal< sc_lv<10> > mul_ln1118_984_fu_653_p1;
    sc_signal< sc_lv<16> > mul_ln1118_985_fu_660_p0;
    sc_signal< sc_lv<25> > sext_ln1118_867_fu_375_p1;
    sc_signal< sc_lv<9> > mul_ln1118_985_fu_660_p1;
    sc_signal< sc_lv<10> > mul_ln1118_986_fu_667_p1;
    sc_signal< sc_lv<9> > mul_ln1118_987_fu_674_p1;
    sc_signal< sc_lv<9> > mul_ln1118_988_fu_681_p1;
    sc_signal< sc_lv<8> > mul_ln1118_989_fu_688_p1;
    sc_signal< sc_lv<9> > mul_ln1118_990_fu_695_p1;
    sc_signal< sc_lv<8> > mul_ln1118_991_fu_702_p1;
    sc_signal< sc_lv<8> > mul_ln1118_992_fu_709_p1;
    sc_signal< sc_lv<10> > mul_ln1118_993_fu_716_p1;
    sc_signal< sc_lv<16> > mul_ln1118_994_fu_723_p0;
    sc_signal< sc_lv<9> > mul_ln1118_994_fu_723_p1;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<16> ap_const_lv16_8A;
    static const sc_lv<16> ap_const_lv16_FD44;
    static const sc_lv<25> ap_const_lv25_1FFFF37;
    static const sc_lv<26> ap_const_lv26_3FFFEE4;
    static const sc_lv<23> ap_const_lv23_3B;
    static const sc_lv<24> ap_const_lv24_FFFFAF;
    static const sc_lv<26> ap_const_lv26_129;
    static const sc_lv<25> ap_const_lv25_BD;
    static const sc_lv<26> ap_const_lv26_3FFFE96;
    static const sc_lv<25> ap_const_lv25_CA;
    static const sc_lv<25> ap_const_lv25_9C;
    static const sc_lv<24> ap_const_lv24_45;
    static const sc_lv<25> ap_const_lv25_1FFFF7D;
    static const sc_lv<24> ap_const_lv24_FFFFB3;
    static const sc_lv<24> ap_const_lv24_7D;
    static const sc_lv<26> ap_const_lv26_18F;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_acc_1_V_fu_608_p2();
    void thread_add_ln1118_fu_212_p2();
    void thread_add_ln703_1285_fu_392_p2();
    void thread_add_ln703_1286_fu_398_p2();
    void thread_add_ln703_1287_fu_584_p2();
    void thread_add_ln703_1288_fu_404_p2();
    void thread_add_ln703_1289_fu_410_p2();
    void thread_add_ln703_1290_fu_416_p2();
    void thread_add_ln703_1291_fu_590_p2();
    void thread_add_ln703_1292_fu_594_p2();
    void thread_add_ln703_1293_fu_531_p2();
    void thread_add_ln703_1294_fu_537_p2();
    void thread_add_ln703_1295_fu_543_p2();
    void thread_add_ln703_1296_fu_549_p2();
    void thread_add_ln703_1297_fu_555_p2();
    void thread_add_ln703_1298_fu_561_p2();
    void thread_add_ln703_1299_fu_567_p2();
    void thread_add_ln703_1300_fu_603_p2();
    void thread_add_ln703_fu_576_p2();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_mul_ln1118_981_fu_632_p1();
    void thread_mul_ln1118_982_fu_639_p1();
    void thread_mul_ln1118_983_fu_646_p1();
    void thread_mul_ln1118_984_fu_653_p1();
    void thread_mul_ln1118_985_fu_660_p0();
    void thread_mul_ln1118_985_fu_660_p1();
    void thread_mul_ln1118_986_fu_667_p1();
    void thread_mul_ln1118_987_fu_674_p1();
    void thread_mul_ln1118_988_fu_681_p1();
    void thread_mul_ln1118_989_fu_688_p1();
    void thread_mul_ln1118_990_fu_695_p1();
    void thread_mul_ln1118_991_fu_702_p1();
    void thread_mul_ln1118_992_fu_709_p1();
    void thread_mul_ln1118_993_fu_716_p1();
    void thread_mul_ln1118_994_fu_723_p0();
    void thread_mul_ln1118_994_fu_723_p1();
    void thread_mul_ln1118_fu_625_p1();
    void thread_sext_ln1118_854_fu_196_p1();
    void thread_sext_ln1118_855_fu_208_p1();
    void thread_sext_ln1118_863_fu_295_p0();
    void thread_sext_ln1118_863_fu_295_p1();
    void thread_sext_ln1118_865_fu_343_p1();
    void thread_sext_ln1118_866_fu_355_p1();
    void thread_sext_ln1118_867_fu_375_p1();
    void thread_sext_ln1118_868_fu_307_p1();
    void thread_sext_ln216_44_fu_249_p1();
    void thread_sext_ln216_45_fu_270_p1();
    void thread_sext_ln216_46_fu_492_p1();
    void thread_sext_ln216_47_fu_505_p1();
    void thread_sext_ln216_fu_228_p1();
    void thread_sext_ln703_257_fu_600_p1();
    void thread_sext_ln703_fu_581_p1();
    void thread_sext_ln708_782_fu_327_p1();
    void thread_sext_ln708_783_fu_388_p1();
    void thread_sext_ln708_784_fu_440_p1();
    void thread_sext_ln708_785_fu_453_p1();
    void thread_sext_ln708_786_fu_466_p1();
    void thread_sext_ln708_787_fu_479_p1();
    void thread_sext_ln708_788_fu_527_p1();
    void thread_sext_ln708_fu_573_p1();
    void thread_shl_ln1118_348_fu_335_p1();
    void thread_shl_ln1118_348_fu_335_p3();
    void thread_shl_ln1118_349_fu_347_p1();
    void thread_shl_ln1118_349_fu_347_p3();
    void thread_shl_ln1118_s_fu_200_p1();
    void thread_shl_ln1118_s_fu_200_p3();
    void thread_shl_ln_fu_188_p1();
    void thread_shl_ln_fu_188_p3();
    void thread_sub_ln1118_268_fu_311_p2();
    void thread_sub_ln1118_fu_359_p2();
    void thread_tmp_497_fu_218_p4();
    void thread_tmp_498_fu_240_p4();
    void thread_tmp_499_fu_261_p4();
    void thread_tmp_500_fu_483_p4();
    void thread_tmp_501_fu_496_p4();
    void thread_tmp_fu_299_p1();
    void thread_tmp_fu_299_p3();
    void thread_trunc_ln708_16_fu_509_p4();
    void thread_trunc_ln708_5_fu_282_p4();
    void thread_trunc_ln708_793_fu_379_p4();
    void thread_trunc_ln708_794_fu_431_p4();
    void thread_trunc_ln708_795_fu_444_p4();
    void thread_trunc_ln708_796_fu_457_p4();
    void thread_trunc_ln708_797_fu_470_p4();
    void thread_trunc_ln708_798_fu_518_p4();
    void thread_trunc_ln708_7_fu_365_p4();
    void thread_trunc_ln708_9_fu_422_p4();
    void thread_trunc_ln708_s_fu_317_p4();
};

}

using namespace ap_rtl;

#endif
