// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_resource_ap_fixed_ap_fixed_config2_mult_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_logic_1 = sc_dt::Log_1;
const bool dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_boolean_1 = true;
const bool dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_boolean_0 = false;
const sc_lv<32> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv32_A = "1010";
const sc_lv<32> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv32_18 = "11000";
const sc_lv<32> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv32_19 = "11001";
const sc_lv<5> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv5_0 = "00000";
const sc_lv<1> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv1_0 = "0";
const sc_lv<32> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv32_15 = "10101";
const sc_lv<32> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv32_16 = "10110";
const sc_lv<32> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv32_17 = "10111";
const sc_lv<3> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv3_0 = "000";
const sc_lv<32> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv32_13 = "10011";
const sc_lv<9> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv9_0 = "000000000";
const sc_lv<16> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv16_8A = "10001010";
const sc_lv<16> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv16_FD44 = "1111110101000100";
const sc_lv<25> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv25_1FFFF37 = "1111111111111111100110111";
const sc_lv<26> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv26_3FFFEE4 = "11111111111111111011100100";
const sc_lv<23> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv23_3B = "111011";
const sc_lv<24> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv24_FFFFAF = "111111111111111110101111";
const sc_lv<26> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv26_129 = "100101001";
const sc_lv<25> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv25_BD = "10111101";
const sc_lv<26> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv26_3FFFE96 = "11111111111111111010010110";
const sc_lv<25> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv25_CA = "11001010";
const sc_lv<25> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv25_9C = "10011100";
const sc_lv<24> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv24_45 = "1000101";
const sc_lv<25> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv25_1FFFF7D = "1111111111111111101111101";
const sc_lv<24> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv24_FFFFB3 = "111111111111111110110011";
const sc_lv<24> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv24_7D = "1111101";
const sc_lv<26> dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_lv26_18F = "110001111";
const sc_logic dense_resource_ap_fixed_ap_fixed_config2_mult_s::ap_const_logic_0 = sc_dt::Log_0;

dense_resource_ap_fixed_ap_fixed_config2_mult_s::dense_resource_ap_fixed_ap_fixed_config2_mult_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    myproject_mul_mul_16s_9s_25_1_1_U4 = new myproject_mul_mul_16s_9s_25_1_1<1,1,16,9,25>("myproject_mul_mul_16s_9s_25_1_1_U4");
    myproject_mul_mul_16s_9s_25_1_1_U4->din0(data_0_V_read);
    myproject_mul_mul_16s_9s_25_1_1_U4->din1(mul_ln1118_fu_625_p1);
    myproject_mul_mul_16s_9s_25_1_1_U4->dout(mul_ln1118_fu_625_p2);
    myproject_mul_mul_16s_10s_26_1_1_U5 = new myproject_mul_mul_16s_10s_26_1_1<1,1,16,10,26>("myproject_mul_mul_16s_10s_26_1_1_U5");
    myproject_mul_mul_16s_10s_26_1_1_U5->din0(data_1_V_read);
    myproject_mul_mul_16s_10s_26_1_1_U5->din1(mul_ln1118_981_fu_632_p1);
    myproject_mul_mul_16s_10s_26_1_1_U5->dout(mul_ln1118_981_fu_632_p2);
    myproject_mul_mul_16s_7ns_23_1_1_U6 = new myproject_mul_mul_16s_7ns_23_1_1<1,1,16,7,23>("myproject_mul_mul_16s_7ns_23_1_1_U6");
    myproject_mul_mul_16s_7ns_23_1_1_U6->din0(data_3_V_read);
    myproject_mul_mul_16s_7ns_23_1_1_U6->din1(mul_ln1118_982_fu_639_p1);
    myproject_mul_mul_16s_7ns_23_1_1_U6->dout(mul_ln1118_982_fu_639_p2);
    myproject_mul_mul_16s_8s_24_1_1_U7 = new myproject_mul_mul_16s_8s_24_1_1<1,1,16,8,24>("myproject_mul_mul_16s_8s_24_1_1_U7");
    myproject_mul_mul_16s_8s_24_1_1_U7->din0(data_4_V_read);
    myproject_mul_mul_16s_8s_24_1_1_U7->din1(mul_ln1118_983_fu_646_p1);
    myproject_mul_mul_16s_8s_24_1_1_U7->dout(mul_ln1118_983_fu_646_p2);
    myproject_mul_mul_16s_10ns_26_1_1_U8 = new myproject_mul_mul_16s_10ns_26_1_1<1,1,16,10,26>("myproject_mul_mul_16s_10ns_26_1_1_U8");
    myproject_mul_mul_16s_10ns_26_1_1_U8->din0(data_5_V_read);
    myproject_mul_mul_16s_10ns_26_1_1_U8->din1(mul_ln1118_984_fu_653_p1);
    myproject_mul_mul_16s_10ns_26_1_1_U8->dout(mul_ln1118_984_fu_653_p2);
    myproject_mul_mul_16s_9ns_25_1_1_U9 = new myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>("myproject_mul_mul_16s_9ns_25_1_1_U9");
    myproject_mul_mul_16s_9ns_25_1_1_U9->din0(mul_ln1118_985_fu_660_p0);
    myproject_mul_mul_16s_9ns_25_1_1_U9->din1(mul_ln1118_985_fu_660_p1);
    myproject_mul_mul_16s_9ns_25_1_1_U9->dout(mul_ln1118_985_fu_660_p2);
    myproject_mul_mul_16s_10s_26_1_1_U10 = new myproject_mul_mul_16s_10s_26_1_1<1,1,16,10,26>("myproject_mul_mul_16s_10s_26_1_1_U10");
    myproject_mul_mul_16s_10s_26_1_1_U10->din0(data_0_V_read);
    myproject_mul_mul_16s_10s_26_1_1_U10->din1(mul_ln1118_986_fu_667_p1);
    myproject_mul_mul_16s_10s_26_1_1_U10->dout(mul_ln1118_986_fu_667_p2);
    myproject_mul_mul_16s_9ns_25_1_1_U11 = new myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>("myproject_mul_mul_16s_9ns_25_1_1_U11");
    myproject_mul_mul_16s_9ns_25_1_1_U11->din0(data_1_V_read);
    myproject_mul_mul_16s_9ns_25_1_1_U11->din1(mul_ln1118_987_fu_674_p1);
    myproject_mul_mul_16s_9ns_25_1_1_U11->dout(mul_ln1118_987_fu_674_p2);
    myproject_mul_mul_16s_9ns_25_1_1_U12 = new myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>("myproject_mul_mul_16s_9ns_25_1_1_U12");
    myproject_mul_mul_16s_9ns_25_1_1_U12->din0(data_2_V_read);
    myproject_mul_mul_16s_9ns_25_1_1_U12->din1(mul_ln1118_988_fu_681_p1);
    myproject_mul_mul_16s_9ns_25_1_1_U12->dout(mul_ln1118_988_fu_681_p2);
    myproject_mul_mul_16s_8ns_24_1_1_U13 = new myproject_mul_mul_16s_8ns_24_1_1<1,1,16,8,24>("myproject_mul_mul_16s_8ns_24_1_1_U13");
    myproject_mul_mul_16s_8ns_24_1_1_U13->din0(data_3_V_read);
    myproject_mul_mul_16s_8ns_24_1_1_U13->din1(mul_ln1118_989_fu_688_p1);
    myproject_mul_mul_16s_8ns_24_1_1_U13->dout(mul_ln1118_989_fu_688_p2);
    myproject_mul_mul_16s_9s_25_1_1_U14 = new myproject_mul_mul_16s_9s_25_1_1<1,1,16,9,25>("myproject_mul_mul_16s_9s_25_1_1_U14");
    myproject_mul_mul_16s_9s_25_1_1_U14->din0(data_4_V_read);
    myproject_mul_mul_16s_9s_25_1_1_U14->din1(mul_ln1118_990_fu_695_p1);
    myproject_mul_mul_16s_9s_25_1_1_U14->dout(mul_ln1118_990_fu_695_p2);
    myproject_mul_mul_16s_8s_24_1_1_U15 = new myproject_mul_mul_16s_8s_24_1_1<1,1,16,8,24>("myproject_mul_mul_16s_8s_24_1_1_U15");
    myproject_mul_mul_16s_8s_24_1_1_U15->din0(data_5_V_read);
    myproject_mul_mul_16s_8s_24_1_1_U15->din1(mul_ln1118_991_fu_702_p1);
    myproject_mul_mul_16s_8s_24_1_1_U15->dout(mul_ln1118_991_fu_702_p2);
    myproject_mul_mul_16s_8ns_24_1_1_U16 = new myproject_mul_mul_16s_8ns_24_1_1<1,1,16,8,24>("myproject_mul_mul_16s_8ns_24_1_1_U16");
    myproject_mul_mul_16s_8ns_24_1_1_U16->din0(data_6_V_read);
    myproject_mul_mul_16s_8ns_24_1_1_U16->din1(mul_ln1118_992_fu_709_p1);
    myproject_mul_mul_16s_8ns_24_1_1_U16->dout(mul_ln1118_992_fu_709_p2);
    myproject_mul_mul_16s_10ns_26_1_1_U17 = new myproject_mul_mul_16s_10ns_26_1_1<1,1,16,10,26>("myproject_mul_mul_16s_10ns_26_1_1_U17");
    myproject_mul_mul_16s_10ns_26_1_1_U17->din0(data_7_V_read);
    myproject_mul_mul_16s_10ns_26_1_1_U17->din1(mul_ln1118_993_fu_716_p1);
    myproject_mul_mul_16s_10ns_26_1_1_U17->dout(mul_ln1118_993_fu_716_p2);
    myproject_mul_mul_16s_9ns_25_1_1_U18 = new myproject_mul_mul_16s_9ns_25_1_1<1,1,16,9,25>("myproject_mul_mul_16s_9ns_25_1_1_U18");
    myproject_mul_mul_16s_9ns_25_1_1_U18->din0(mul_ln1118_994_fu_723_p0);
    myproject_mul_mul_16s_9ns_25_1_1_U18->din1(mul_ln1118_994_fu_723_p1);
    myproject_mul_mul_16s_9ns_25_1_1_U18->dout(mul_ln1118_994_fu_723_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_1_V_fu_608_p2);
    sensitive << ( add_ln703_1296_reg_755 );
    sensitive << ( add_ln703_1300_fu_603_p2 );

    SC_METHOD(thread_add_ln1118_fu_212_p2);
    sensitive << ( sext_ln1118_854_fu_196_p1 );
    sensitive << ( sext_ln1118_855_fu_208_p1 );

    SC_METHOD(thread_add_ln703_1285_fu_392_p2);
    sensitive << ( sext_ln216_45_fu_270_p1 );
    sensitive << ( sext_ln216_44_fu_249_p1 );

    SC_METHOD(thread_add_ln703_1286_fu_398_p2);
    sensitive << ( sext_ln216_fu_228_p1 );
    sensitive << ( add_ln703_1285_fu_392_p2 );

    SC_METHOD(thread_add_ln703_1287_fu_584_p2);
    sensitive << ( add_ln703_fu_576_p2 );
    sensitive << ( sext_ln703_fu_581_p1 );

    SC_METHOD(thread_add_ln703_1288_fu_404_p2);
    sensitive << ( sext_ln708_782_fu_327_p1 );
    sensitive << ( trunc_ln708_5_fu_282_p4 );

    SC_METHOD(thread_add_ln703_1289_fu_410_p2);
    sensitive << ( sext_ln708_783_fu_388_p1 );

    SC_METHOD(thread_add_ln703_1290_fu_416_p2);
    sensitive << ( trunc_ln708_7_fu_365_p4 );
    sensitive << ( add_ln703_1289_fu_410_p2 );

    SC_METHOD(thread_add_ln703_1291_fu_590_p2);
    sensitive << ( add_ln703_1288_reg_745 );
    sensitive << ( add_ln703_1290_reg_750 );

    SC_METHOD(thread_add_ln703_1292_fu_594_p2);
    sensitive << ( add_ln703_1287_fu_584_p2 );
    sensitive << ( add_ln703_1291_fu_590_p2 );

    SC_METHOD(thread_add_ln703_1293_fu_531_p2);
    sensitive << ( sext_ln708_784_fu_440_p1 );
    sensitive << ( trunc_ln708_9_fu_422_p4 );

    SC_METHOD(thread_add_ln703_1294_fu_537_p2);
    sensitive << ( sext_ln708_787_fu_479_p1 );
    sensitive << ( sext_ln708_786_fu_466_p1 );

    SC_METHOD(thread_add_ln703_1295_fu_543_p2);
    sensitive << ( sext_ln708_785_fu_453_p1 );
    sensitive << ( add_ln703_1294_fu_537_p2 );

    SC_METHOD(thread_add_ln703_1296_fu_549_p2);
    sensitive << ( add_ln703_1293_fu_531_p2 );
    sensitive << ( add_ln703_1295_fu_543_p2 );

    SC_METHOD(thread_add_ln703_1297_fu_555_p2);
    sensitive << ( sext_ln216_47_fu_505_p1 );
    sensitive << ( sext_ln216_46_fu_492_p1 );

    SC_METHOD(thread_add_ln703_1298_fu_561_p2);
    sensitive << ( sext_ln708_788_fu_527_p1 );

    SC_METHOD(thread_add_ln703_1299_fu_567_p2);
    sensitive << ( trunc_ln708_16_fu_509_p4 );
    sensitive << ( add_ln703_1298_fu_561_p2 );

    SC_METHOD(thread_add_ln703_1300_fu_603_p2);
    sensitive << ( add_ln703_1299_reg_765 );
    sensitive << ( sext_ln703_257_fu_600_p1 );

    SC_METHOD(thread_add_ln703_fu_576_p2);
    sensitive << ( trunc_ln708_1_reg_735 );
    sensitive << ( sext_ln708_fu_573_p1 );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( add_ln703_1292_fu_594_p2 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( acc_1_V_fu_608_p2 );

    SC_METHOD(thread_mul_ln1118_981_fu_632_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_982_fu_639_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_983_fu_646_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_984_fu_653_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_985_fu_660_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_867_fu_375_p1 );

    SC_METHOD(thread_mul_ln1118_985_fu_660_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_986_fu_667_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_987_fu_674_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_988_fu_681_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_989_fu_688_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_990_fu_695_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_991_fu_702_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_992_fu_709_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_993_fu_716_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_994_fu_723_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( sext_ln1118_867_fu_375_p1 );

    SC_METHOD(thread_mul_ln1118_994_fu_723_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_fu_625_p1);
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_854_fu_196_p1);
    sensitive << ( shl_ln_fu_188_p3 );

    SC_METHOD(thread_sext_ln1118_855_fu_208_p1);
    sensitive << ( shl_ln1118_s_fu_200_p3 );

    SC_METHOD(thread_sext_ln1118_863_fu_295_p0);
    sensitive << ( data_6_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_sext_ln1118_863_fu_295_p1);
    sensitive << ( sext_ln1118_863_fu_295_p0 );

    SC_METHOD(thread_sext_ln1118_865_fu_343_p1);
    sensitive << ( shl_ln1118_348_fu_335_p3 );

    SC_METHOD(thread_sext_ln1118_866_fu_355_p1);
    sensitive << ( shl_ln1118_349_fu_347_p3 );

    SC_METHOD(thread_sext_ln1118_867_fu_375_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_sext_ln1118_868_fu_307_p1);
    sensitive << ( tmp_fu_299_p3 );

    SC_METHOD(thread_sext_ln216_44_fu_249_p1);
    sensitive << ( tmp_498_fu_240_p4 );

    SC_METHOD(thread_sext_ln216_45_fu_270_p1);
    sensitive << ( tmp_499_fu_261_p4 );

    SC_METHOD(thread_sext_ln216_46_fu_492_p1);
    sensitive << ( tmp_500_fu_483_p4 );

    SC_METHOD(thread_sext_ln216_47_fu_505_p1);
    sensitive << ( tmp_501_fu_496_p4 );

    SC_METHOD(thread_sext_ln216_fu_228_p1);
    sensitive << ( tmp_497_fu_218_p4 );

    SC_METHOD(thread_sext_ln703_257_fu_600_p1);
    sensitive << ( add_ln703_1297_reg_760 );

    SC_METHOD(thread_sext_ln703_fu_581_p1);
    sensitive << ( add_ln703_1286_reg_740 );

    SC_METHOD(thread_sext_ln708_782_fu_327_p1);
    sensitive << ( trunc_ln708_s_fu_317_p4 );

    SC_METHOD(thread_sext_ln708_783_fu_388_p1);
    sensitive << ( trunc_ln708_793_fu_379_p4 );

    SC_METHOD(thread_sext_ln708_784_fu_440_p1);
    sensitive << ( trunc_ln708_794_fu_431_p4 );

    SC_METHOD(thread_sext_ln708_785_fu_453_p1);
    sensitive << ( trunc_ln708_795_fu_444_p4 );

    SC_METHOD(thread_sext_ln708_786_fu_466_p1);
    sensitive << ( trunc_ln708_796_fu_457_p4 );

    SC_METHOD(thread_sext_ln708_787_fu_479_p1);
    sensitive << ( trunc_ln708_797_fu_470_p4 );

    SC_METHOD(thread_sext_ln708_788_fu_527_p1);
    sensitive << ( trunc_ln708_798_fu_518_p4 );

    SC_METHOD(thread_sext_ln708_fu_573_p1);
    sensitive << ( trunc_ln_reg_730 );

    SC_METHOD(thread_shl_ln1118_348_fu_335_p1);
    sensitive << ( data_7_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_348_fu_335_p3);
    sensitive << ( shl_ln1118_348_fu_335_p1 );

    SC_METHOD(thread_shl_ln1118_349_fu_347_p1);
    sensitive << ( data_7_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_349_fu_347_p3);
    sensitive << ( shl_ln1118_349_fu_347_p1 );

    SC_METHOD(thread_shl_ln1118_s_fu_200_p1);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln1118_s_fu_200_p3);
    sensitive << ( shl_ln1118_s_fu_200_p1 );

    SC_METHOD(thread_shl_ln_fu_188_p1);
    sensitive << ( data_2_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_shl_ln_fu_188_p3);
    sensitive << ( shl_ln_fu_188_p1 );

    SC_METHOD(thread_sub_ln1118_268_fu_311_p2);
    sensitive << ( sext_ln1118_863_fu_295_p1 );
    sensitive << ( sext_ln1118_868_fu_307_p1 );

    SC_METHOD(thread_sub_ln1118_fu_359_p2);
    sensitive << ( sext_ln1118_865_fu_343_p1 );
    sensitive << ( sext_ln1118_866_fu_355_p1 );

    SC_METHOD(thread_tmp_497_fu_218_p4);
    sensitive << ( add_ln1118_fu_212_p2 );

    SC_METHOD(thread_tmp_498_fu_240_p4);
    sensitive << ( mul_ln1118_982_fu_639_p2 );

    SC_METHOD(thread_tmp_499_fu_261_p4);
    sensitive << ( mul_ln1118_983_fu_646_p2 );

    SC_METHOD(thread_tmp_500_fu_483_p4);
    sensitive << ( mul_ln1118_991_fu_702_p2 );

    SC_METHOD(thread_tmp_501_fu_496_p4);
    sensitive << ( mul_ln1118_992_fu_709_p2 );

    SC_METHOD(thread_tmp_fu_299_p1);
    sensitive << ( data_6_V_read );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_fu_299_p3);
    sensitive << ( tmp_fu_299_p1 );

    SC_METHOD(thread_trunc_ln708_16_fu_509_p4);
    sensitive << ( mul_ln1118_993_fu_716_p2 );

    SC_METHOD(thread_trunc_ln708_5_fu_282_p4);
    sensitive << ( mul_ln1118_984_fu_653_p2 );

    SC_METHOD(thread_trunc_ln708_793_fu_379_p4);
    sensitive << ( mul_ln1118_985_fu_660_p2 );

    SC_METHOD(thread_trunc_ln708_794_fu_431_p4);
    sensitive << ( mul_ln1118_987_fu_674_p2 );

    SC_METHOD(thread_trunc_ln708_795_fu_444_p4);
    sensitive << ( mul_ln1118_988_fu_681_p2 );

    SC_METHOD(thread_trunc_ln708_796_fu_457_p4);
    sensitive << ( mul_ln1118_989_fu_688_p2 );

    SC_METHOD(thread_trunc_ln708_797_fu_470_p4);
    sensitive << ( mul_ln1118_990_fu_695_p2 );

    SC_METHOD(thread_trunc_ln708_798_fu_518_p4);
    sensitive << ( mul_ln1118_994_fu_723_p2 );

    SC_METHOD(thread_trunc_ln708_7_fu_365_p4);
    sensitive << ( sub_ln1118_fu_359_p2 );

    SC_METHOD(thread_trunc_ln708_9_fu_422_p4);
    sensitive << ( mul_ln1118_986_fu_667_p2 );

    SC_METHOD(thread_trunc_ln708_s_fu_317_p4);
    sensitive << ( sub_ln1118_268_fu_311_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_resource_ap_fixed_ap_fixed_config2_mult_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, trunc_ln_reg_730, "trunc_ln_reg_730");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, trunc_ln708_1_reg_735, "trunc_ln708_1_reg_735");
    sc_trace(mVcdFile, add_ln703_1286_fu_398_p2, "add_ln703_1286_fu_398_p2");
    sc_trace(mVcdFile, add_ln703_1286_reg_740, "add_ln703_1286_reg_740");
    sc_trace(mVcdFile, add_ln703_1288_fu_404_p2, "add_ln703_1288_fu_404_p2");
    sc_trace(mVcdFile, add_ln703_1288_reg_745, "add_ln703_1288_reg_745");
    sc_trace(mVcdFile, add_ln703_1290_fu_416_p2, "add_ln703_1290_fu_416_p2");
    sc_trace(mVcdFile, add_ln703_1290_reg_750, "add_ln703_1290_reg_750");
    sc_trace(mVcdFile, add_ln703_1296_fu_549_p2, "add_ln703_1296_fu_549_p2");
    sc_trace(mVcdFile, add_ln703_1296_reg_755, "add_ln703_1296_reg_755");
    sc_trace(mVcdFile, add_ln703_1297_fu_555_p2, "add_ln703_1297_fu_555_p2");
    sc_trace(mVcdFile, add_ln703_1297_reg_760, "add_ln703_1297_reg_760");
    sc_trace(mVcdFile, add_ln703_1299_fu_567_p2, "add_ln703_1299_fu_567_p2");
    sc_trace(mVcdFile, add_ln703_1299_reg_765, "add_ln703_1299_reg_765");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, mul_ln1118_fu_625_p2, "mul_ln1118_fu_625_p2");
    sc_trace(mVcdFile, mul_ln1118_981_fu_632_p2, "mul_ln1118_981_fu_632_p2");
    sc_trace(mVcdFile, shl_ln_fu_188_p1, "shl_ln_fu_188_p1");
    sc_trace(mVcdFile, shl_ln_fu_188_p3, "shl_ln_fu_188_p3");
    sc_trace(mVcdFile, shl_ln1118_s_fu_200_p1, "shl_ln1118_s_fu_200_p1");
    sc_trace(mVcdFile, shl_ln1118_s_fu_200_p3, "shl_ln1118_s_fu_200_p3");
    sc_trace(mVcdFile, sext_ln1118_854_fu_196_p1, "sext_ln1118_854_fu_196_p1");
    sc_trace(mVcdFile, sext_ln1118_855_fu_208_p1, "sext_ln1118_855_fu_208_p1");
    sc_trace(mVcdFile, add_ln1118_fu_212_p2, "add_ln1118_fu_212_p2");
    sc_trace(mVcdFile, tmp_497_fu_218_p4, "tmp_497_fu_218_p4");
    sc_trace(mVcdFile, mul_ln1118_982_fu_639_p2, "mul_ln1118_982_fu_639_p2");
    sc_trace(mVcdFile, tmp_498_fu_240_p4, "tmp_498_fu_240_p4");
    sc_trace(mVcdFile, mul_ln1118_983_fu_646_p2, "mul_ln1118_983_fu_646_p2");
    sc_trace(mVcdFile, tmp_499_fu_261_p4, "tmp_499_fu_261_p4");
    sc_trace(mVcdFile, mul_ln1118_984_fu_653_p2, "mul_ln1118_984_fu_653_p2");
    sc_trace(mVcdFile, sext_ln1118_863_fu_295_p0, "sext_ln1118_863_fu_295_p0");
    sc_trace(mVcdFile, tmp_fu_299_p1, "tmp_fu_299_p1");
    sc_trace(mVcdFile, tmp_fu_299_p3, "tmp_fu_299_p3");
    sc_trace(mVcdFile, sext_ln1118_863_fu_295_p1, "sext_ln1118_863_fu_295_p1");
    sc_trace(mVcdFile, sext_ln1118_868_fu_307_p1, "sext_ln1118_868_fu_307_p1");
    sc_trace(mVcdFile, sub_ln1118_268_fu_311_p2, "sub_ln1118_268_fu_311_p2");
    sc_trace(mVcdFile, trunc_ln708_s_fu_317_p4, "trunc_ln708_s_fu_317_p4");
    sc_trace(mVcdFile, shl_ln1118_348_fu_335_p1, "shl_ln1118_348_fu_335_p1");
    sc_trace(mVcdFile, shl_ln1118_348_fu_335_p3, "shl_ln1118_348_fu_335_p3");
    sc_trace(mVcdFile, shl_ln1118_349_fu_347_p1, "shl_ln1118_349_fu_347_p1");
    sc_trace(mVcdFile, shl_ln1118_349_fu_347_p3, "shl_ln1118_349_fu_347_p3");
    sc_trace(mVcdFile, sext_ln1118_865_fu_343_p1, "sext_ln1118_865_fu_343_p1");
    sc_trace(mVcdFile, sext_ln1118_866_fu_355_p1, "sext_ln1118_866_fu_355_p1");
    sc_trace(mVcdFile, sub_ln1118_fu_359_p2, "sub_ln1118_fu_359_p2");
    sc_trace(mVcdFile, mul_ln1118_985_fu_660_p2, "mul_ln1118_985_fu_660_p2");
    sc_trace(mVcdFile, trunc_ln708_793_fu_379_p4, "trunc_ln708_793_fu_379_p4");
    sc_trace(mVcdFile, sext_ln216_45_fu_270_p1, "sext_ln216_45_fu_270_p1");
    sc_trace(mVcdFile, sext_ln216_44_fu_249_p1, "sext_ln216_44_fu_249_p1");
    sc_trace(mVcdFile, sext_ln216_fu_228_p1, "sext_ln216_fu_228_p1");
    sc_trace(mVcdFile, add_ln703_1285_fu_392_p2, "add_ln703_1285_fu_392_p2");
    sc_trace(mVcdFile, sext_ln708_782_fu_327_p1, "sext_ln708_782_fu_327_p1");
    sc_trace(mVcdFile, trunc_ln708_5_fu_282_p4, "trunc_ln708_5_fu_282_p4");
    sc_trace(mVcdFile, sext_ln708_783_fu_388_p1, "sext_ln708_783_fu_388_p1");
    sc_trace(mVcdFile, trunc_ln708_7_fu_365_p4, "trunc_ln708_7_fu_365_p4");
    sc_trace(mVcdFile, add_ln703_1289_fu_410_p2, "add_ln703_1289_fu_410_p2");
    sc_trace(mVcdFile, mul_ln1118_986_fu_667_p2, "mul_ln1118_986_fu_667_p2");
    sc_trace(mVcdFile, mul_ln1118_987_fu_674_p2, "mul_ln1118_987_fu_674_p2");
    sc_trace(mVcdFile, trunc_ln708_794_fu_431_p4, "trunc_ln708_794_fu_431_p4");
    sc_trace(mVcdFile, mul_ln1118_988_fu_681_p2, "mul_ln1118_988_fu_681_p2");
    sc_trace(mVcdFile, trunc_ln708_795_fu_444_p4, "trunc_ln708_795_fu_444_p4");
    sc_trace(mVcdFile, mul_ln1118_989_fu_688_p2, "mul_ln1118_989_fu_688_p2");
    sc_trace(mVcdFile, trunc_ln708_796_fu_457_p4, "trunc_ln708_796_fu_457_p4");
    sc_trace(mVcdFile, mul_ln1118_990_fu_695_p2, "mul_ln1118_990_fu_695_p2");
    sc_trace(mVcdFile, trunc_ln708_797_fu_470_p4, "trunc_ln708_797_fu_470_p4");
    sc_trace(mVcdFile, mul_ln1118_991_fu_702_p2, "mul_ln1118_991_fu_702_p2");
    sc_trace(mVcdFile, tmp_500_fu_483_p4, "tmp_500_fu_483_p4");
    sc_trace(mVcdFile, mul_ln1118_992_fu_709_p2, "mul_ln1118_992_fu_709_p2");
    sc_trace(mVcdFile, tmp_501_fu_496_p4, "tmp_501_fu_496_p4");
    sc_trace(mVcdFile, mul_ln1118_993_fu_716_p2, "mul_ln1118_993_fu_716_p2");
    sc_trace(mVcdFile, mul_ln1118_994_fu_723_p2, "mul_ln1118_994_fu_723_p2");
    sc_trace(mVcdFile, trunc_ln708_798_fu_518_p4, "trunc_ln708_798_fu_518_p4");
    sc_trace(mVcdFile, sext_ln708_784_fu_440_p1, "sext_ln708_784_fu_440_p1");
    sc_trace(mVcdFile, trunc_ln708_9_fu_422_p4, "trunc_ln708_9_fu_422_p4");
    sc_trace(mVcdFile, sext_ln708_787_fu_479_p1, "sext_ln708_787_fu_479_p1");
    sc_trace(mVcdFile, sext_ln708_786_fu_466_p1, "sext_ln708_786_fu_466_p1");
    sc_trace(mVcdFile, sext_ln708_785_fu_453_p1, "sext_ln708_785_fu_453_p1");
    sc_trace(mVcdFile, add_ln703_1294_fu_537_p2, "add_ln703_1294_fu_537_p2");
    sc_trace(mVcdFile, add_ln703_1293_fu_531_p2, "add_ln703_1293_fu_531_p2");
    sc_trace(mVcdFile, add_ln703_1295_fu_543_p2, "add_ln703_1295_fu_543_p2");
    sc_trace(mVcdFile, sext_ln216_47_fu_505_p1, "sext_ln216_47_fu_505_p1");
    sc_trace(mVcdFile, sext_ln216_46_fu_492_p1, "sext_ln216_46_fu_492_p1");
    sc_trace(mVcdFile, sext_ln708_788_fu_527_p1, "sext_ln708_788_fu_527_p1");
    sc_trace(mVcdFile, trunc_ln708_16_fu_509_p4, "trunc_ln708_16_fu_509_p4");
    sc_trace(mVcdFile, add_ln703_1298_fu_561_p2, "add_ln703_1298_fu_561_p2");
    sc_trace(mVcdFile, sext_ln708_fu_573_p1, "sext_ln708_fu_573_p1");
    sc_trace(mVcdFile, add_ln703_fu_576_p2, "add_ln703_fu_576_p2");
    sc_trace(mVcdFile, sext_ln703_fu_581_p1, "sext_ln703_fu_581_p1");
    sc_trace(mVcdFile, add_ln703_1287_fu_584_p2, "add_ln703_1287_fu_584_p2");
    sc_trace(mVcdFile, add_ln703_1291_fu_590_p2, "add_ln703_1291_fu_590_p2");
    sc_trace(mVcdFile, sext_ln703_257_fu_600_p1, "sext_ln703_257_fu_600_p1");
    sc_trace(mVcdFile, add_ln703_1300_fu_603_p2, "add_ln703_1300_fu_603_p2");
    sc_trace(mVcdFile, add_ln703_1292_fu_594_p2, "add_ln703_1292_fu_594_p2");
    sc_trace(mVcdFile, acc_1_V_fu_608_p2, "acc_1_V_fu_608_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_625_p1, "mul_ln1118_fu_625_p1");
    sc_trace(mVcdFile, mul_ln1118_981_fu_632_p1, "mul_ln1118_981_fu_632_p1");
    sc_trace(mVcdFile, mul_ln1118_982_fu_639_p1, "mul_ln1118_982_fu_639_p1");
    sc_trace(mVcdFile, mul_ln1118_983_fu_646_p1, "mul_ln1118_983_fu_646_p1");
    sc_trace(mVcdFile, mul_ln1118_984_fu_653_p1, "mul_ln1118_984_fu_653_p1");
    sc_trace(mVcdFile, mul_ln1118_985_fu_660_p0, "mul_ln1118_985_fu_660_p0");
    sc_trace(mVcdFile, sext_ln1118_867_fu_375_p1, "sext_ln1118_867_fu_375_p1");
    sc_trace(mVcdFile, mul_ln1118_985_fu_660_p1, "mul_ln1118_985_fu_660_p1");
    sc_trace(mVcdFile, mul_ln1118_986_fu_667_p1, "mul_ln1118_986_fu_667_p1");
    sc_trace(mVcdFile, mul_ln1118_987_fu_674_p1, "mul_ln1118_987_fu_674_p1");
    sc_trace(mVcdFile, mul_ln1118_988_fu_681_p1, "mul_ln1118_988_fu_681_p1");
    sc_trace(mVcdFile, mul_ln1118_989_fu_688_p1, "mul_ln1118_989_fu_688_p1");
    sc_trace(mVcdFile, mul_ln1118_990_fu_695_p1, "mul_ln1118_990_fu_695_p1");
    sc_trace(mVcdFile, mul_ln1118_991_fu_702_p1, "mul_ln1118_991_fu_702_p1");
    sc_trace(mVcdFile, mul_ln1118_992_fu_709_p1, "mul_ln1118_992_fu_709_p1");
    sc_trace(mVcdFile, mul_ln1118_993_fu_716_p1, "mul_ln1118_993_fu_716_p1");
    sc_trace(mVcdFile, mul_ln1118_994_fu_723_p0, "mul_ln1118_994_fu_723_p0");
    sc_trace(mVcdFile, mul_ln1118_994_fu_723_p1, "mul_ln1118_994_fu_723_p1");
#endif

    }
}

dense_resource_ap_fixed_ap_fixed_config2_mult_s::~dense_resource_ap_fixed_ap_fixed_config2_mult_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete myproject_mul_mul_16s_9s_25_1_1_U4;
    delete myproject_mul_mul_16s_10s_26_1_1_U5;
    delete myproject_mul_mul_16s_7ns_23_1_1_U6;
    delete myproject_mul_mul_16s_8s_24_1_1_U7;
    delete myproject_mul_mul_16s_10ns_26_1_1_U8;
    delete myproject_mul_mul_16s_9ns_25_1_1_U9;
    delete myproject_mul_mul_16s_10s_26_1_1_U10;
    delete myproject_mul_mul_16s_9ns_25_1_1_U11;
    delete myproject_mul_mul_16s_9ns_25_1_1_U12;
    delete myproject_mul_mul_16s_8ns_24_1_1_U13;
    delete myproject_mul_mul_16s_9s_25_1_1_U14;
    delete myproject_mul_mul_16s_8s_24_1_1_U15;
    delete myproject_mul_mul_16s_8ns_24_1_1_U16;
    delete myproject_mul_mul_16s_10ns_26_1_1_U17;
    delete myproject_mul_mul_16s_9ns_25_1_1_U18;
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        add_ln703_1286_reg_740 = add_ln703_1286_fu_398_p2.read();
        add_ln703_1288_reg_745 = add_ln703_1288_fu_404_p2.read();
        add_ln703_1290_reg_750 = add_ln703_1290_fu_416_p2.read();
        add_ln703_1296_reg_755 = add_ln703_1296_fu_549_p2.read();
        add_ln703_1297_reg_760 = add_ln703_1297_fu_555_p2.read();
        add_ln703_1299_reg_765 = add_ln703_1299_fu_567_p2.read();
        trunc_ln708_1_reg_735 = mul_ln1118_981_fu_632_p2.read().range(25, 10);
        trunc_ln_reg_730 = mul_ln1118_fu_625_p2.read().range(24, 10);
    }
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_acc_1_V_fu_608_p2() {
    acc_1_V_fu_608_p2 = (!add_ln703_1296_reg_755.read().is_01() || !add_ln703_1300_fu_603_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1296_reg_755.read()) + sc_biguint<16>(add_ln703_1300_fu_603_p2.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln1118_fu_212_p2() {
    add_ln1118_fu_212_p2 = (!sext_ln1118_854_fu_196_p1.read().is_01() || !sext_ln1118_855_fu_208_p1.read().is_01())? sc_lv<22>(): (sc_bigint<22>(sext_ln1118_854_fu_196_p1.read()) + sc_bigint<22>(sext_ln1118_855_fu_208_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1285_fu_392_p2() {
    add_ln703_1285_fu_392_p2 = (!sext_ln216_45_fu_270_p1.read().is_01() || !sext_ln216_44_fu_249_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln216_45_fu_270_p1.read()) + sc_bigint<15>(sext_ln216_44_fu_249_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1286_fu_398_p2() {
    add_ln703_1286_fu_398_p2 = (!sext_ln216_fu_228_p1.read().is_01() || !add_ln703_1285_fu_392_p2.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln216_fu_228_p1.read()) + sc_biguint<15>(add_ln703_1285_fu_392_p2.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1287_fu_584_p2() {
    add_ln703_1287_fu_584_p2 = (!add_ln703_fu_576_p2.read().is_01() || !sext_ln703_fu_581_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_fu_576_p2.read()) + sc_bigint<16>(sext_ln703_fu_581_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1288_fu_404_p2() {
    add_ln703_1288_fu_404_p2 = (!sext_ln708_782_fu_327_p1.read().is_01() || !trunc_ln708_5_fu_282_p4.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_782_fu_327_p1.read()) + sc_biguint<16>(trunc_ln708_5_fu_282_p4.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1289_fu_410_p2() {
    add_ln703_1289_fu_410_p2 = (!sext_ln708_783_fu_388_p1.read().is_01() || !ap_const_lv16_8A.is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_783_fu_388_p1.read()) + sc_biguint<16>(ap_const_lv16_8A));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1290_fu_416_p2() {
    add_ln703_1290_fu_416_p2 = (!trunc_ln708_7_fu_365_p4.read().is_01() || !add_ln703_1289_fu_410_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_7_fu_365_p4.read()) + sc_biguint<16>(add_ln703_1289_fu_410_p2.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1291_fu_590_p2() {
    add_ln703_1291_fu_590_p2 = (!add_ln703_1288_reg_745.read().is_01() || !add_ln703_1290_reg_750.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1288_reg_745.read()) + sc_biguint<16>(add_ln703_1290_reg_750.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1292_fu_594_p2() {
    add_ln703_1292_fu_594_p2 = (!add_ln703_1287_fu_584_p2.read().is_01() || !add_ln703_1291_fu_590_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1287_fu_584_p2.read()) + sc_biguint<16>(add_ln703_1291_fu_590_p2.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1293_fu_531_p2() {
    add_ln703_1293_fu_531_p2 = (!sext_ln708_784_fu_440_p1.read().is_01() || !trunc_ln708_9_fu_422_p4.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_784_fu_440_p1.read()) + sc_biguint<16>(trunc_ln708_9_fu_422_p4.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1294_fu_537_p2() {
    add_ln703_1294_fu_537_p2 = (!sext_ln708_787_fu_479_p1.read().is_01() || !sext_ln708_786_fu_466_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_787_fu_479_p1.read()) + sc_bigint<16>(sext_ln708_786_fu_466_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1295_fu_543_p2() {
    add_ln703_1295_fu_543_p2 = (!sext_ln708_785_fu_453_p1.read().is_01() || !add_ln703_1294_fu_537_p2.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_785_fu_453_p1.read()) + sc_biguint<16>(add_ln703_1294_fu_537_p2.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1296_fu_549_p2() {
    add_ln703_1296_fu_549_p2 = (!add_ln703_1293_fu_531_p2.read().is_01() || !add_ln703_1295_fu_543_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1293_fu_531_p2.read()) + sc_biguint<16>(add_ln703_1295_fu_543_p2.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1297_fu_555_p2() {
    add_ln703_1297_fu_555_p2 = (!sext_ln216_47_fu_505_p1.read().is_01() || !sext_ln216_46_fu_492_p1.read().is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln216_47_fu_505_p1.read()) + sc_bigint<15>(sext_ln216_46_fu_492_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1298_fu_561_p2() {
    add_ln703_1298_fu_561_p2 = (!sext_ln708_788_fu_527_p1.read().is_01() || !ap_const_lv16_FD44.is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_788_fu_527_p1.read()) + sc_bigint<16>(ap_const_lv16_FD44));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1299_fu_567_p2() {
    add_ln703_1299_fu_567_p2 = (!trunc_ln708_16_fu_509_p4.read().is_01() || !add_ln703_1298_fu_561_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_16_fu_509_p4.read()) + sc_biguint<16>(add_ln703_1298_fu_561_p2.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_1300_fu_603_p2() {
    add_ln703_1300_fu_603_p2 = (!sext_ln703_257_fu_600_p1.read().is_01() || !add_ln703_1299_reg_765.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln703_257_fu_600_p1.read()) + sc_biguint<16>(add_ln703_1299_reg_765.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_add_ln703_fu_576_p2() {
    add_ln703_fu_576_p2 = (!trunc_ln708_1_reg_735.read().is_01() || !sext_ln708_fu_573_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_1_reg_735.read()) + sc_bigint<16>(sext_ln708_fu_573_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_ap_return_0() {
    ap_return_0 = add_ln703_1292_fu_594_p2.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_ap_return_1() {
    ap_return_1 = acc_1_V_fu_608_p2.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_981_fu_632_p1() {
    mul_ln1118_981_fu_632_p1 =  (sc_lv<10>) (ap_const_lv26_3FFFEE4);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_982_fu_639_p1() {
    mul_ln1118_982_fu_639_p1 =  (sc_lv<7>) (ap_const_lv23_3B);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_983_fu_646_p1() {
    mul_ln1118_983_fu_646_p1 =  (sc_lv<8>) (ap_const_lv24_FFFFAF);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_984_fu_653_p1() {
    mul_ln1118_984_fu_653_p1 =  (sc_lv<10>) (ap_const_lv26_129);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_985_fu_660_p0() {
    mul_ln1118_985_fu_660_p0 =  (sc_lv<16>) (sext_ln1118_867_fu_375_p1.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_985_fu_660_p1() {
    mul_ln1118_985_fu_660_p1 =  (sc_lv<9>) (ap_const_lv25_BD);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_986_fu_667_p1() {
    mul_ln1118_986_fu_667_p1 =  (sc_lv<10>) (ap_const_lv26_3FFFE96);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_987_fu_674_p1() {
    mul_ln1118_987_fu_674_p1 =  (sc_lv<9>) (ap_const_lv25_CA);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_988_fu_681_p1() {
    mul_ln1118_988_fu_681_p1 =  (sc_lv<9>) (ap_const_lv25_9C);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_989_fu_688_p1() {
    mul_ln1118_989_fu_688_p1 =  (sc_lv<8>) (ap_const_lv24_45);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_990_fu_695_p1() {
    mul_ln1118_990_fu_695_p1 =  (sc_lv<9>) (ap_const_lv25_1FFFF7D);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_991_fu_702_p1() {
    mul_ln1118_991_fu_702_p1 =  (sc_lv<8>) (ap_const_lv24_FFFFB3);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_992_fu_709_p1() {
    mul_ln1118_992_fu_709_p1 =  (sc_lv<8>) (ap_const_lv24_7D);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_993_fu_716_p1() {
    mul_ln1118_993_fu_716_p1 =  (sc_lv<10>) (ap_const_lv26_18F);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_994_fu_723_p0() {
    mul_ln1118_994_fu_723_p0 =  (sc_lv<16>) (sext_ln1118_867_fu_375_p1.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_994_fu_723_p1() {
    mul_ln1118_994_fu_723_p1 =  (sc_lv<9>) (ap_const_lv25_9C);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_mul_ln1118_fu_625_p1() {
    mul_ln1118_fu_625_p1 =  (sc_lv<9>) (ap_const_lv25_1FFFF37);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_854_fu_196_p1() {
    sext_ln1118_854_fu_196_p1 = esl_sext<22,21>(shl_ln_fu_188_p3.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_855_fu_208_p1() {
    sext_ln1118_855_fu_208_p1 = esl_sext<22,17>(shl_ln1118_s_fu_200_p3.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_863_fu_295_p0() {
    sext_ln1118_863_fu_295_p0 = data_6_V_read.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_863_fu_295_p1() {
    sext_ln1118_863_fu_295_p1 = esl_sext<20,16>(sext_ln1118_863_fu_295_p0.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_865_fu_343_p1() {
    sext_ln1118_865_fu_343_p1 = esl_sext<26,25>(shl_ln1118_348_fu_335_p3.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_866_fu_355_p1() {
    sext_ln1118_866_fu_355_p1 = esl_sext<26,21>(shl_ln1118_349_fu_347_p3.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_867_fu_375_p1() {
    sext_ln1118_867_fu_375_p1 = esl_sext<25,16>(data_8_V_read.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln1118_868_fu_307_p1() {
    sext_ln1118_868_fu_307_p1 = esl_sext<20,19>(tmp_fu_299_p3.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln216_44_fu_249_p1() {
    sext_ln216_44_fu_249_p1 = esl_sext<15,13>(tmp_498_fu_240_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln216_45_fu_270_p1() {
    sext_ln216_45_fu_270_p1 = esl_sext<15,14>(tmp_499_fu_261_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln216_46_fu_492_p1() {
    sext_ln216_46_fu_492_p1 = esl_sext<15,14>(tmp_500_fu_483_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln216_47_fu_505_p1() {
    sext_ln216_47_fu_505_p1 = esl_sext<15,14>(tmp_501_fu_496_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln216_fu_228_p1() {
    sext_ln216_fu_228_p1 = esl_sext<15,12>(tmp_497_fu_218_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln703_257_fu_600_p1() {
    sext_ln703_257_fu_600_p1 = esl_sext<16,15>(add_ln703_1297_reg_760.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln703_fu_581_p1() {
    sext_ln703_fu_581_p1 = esl_sext<16,15>(add_ln703_1286_reg_740.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_782_fu_327_p1() {
    sext_ln708_782_fu_327_p1 = esl_sext<16,10>(trunc_ln708_s_fu_317_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_783_fu_388_p1() {
    sext_ln708_783_fu_388_p1 = esl_sext<16,15>(trunc_ln708_793_fu_379_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_784_fu_440_p1() {
    sext_ln708_784_fu_440_p1 = esl_sext<16,15>(trunc_ln708_794_fu_431_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_785_fu_453_p1() {
    sext_ln708_785_fu_453_p1 = esl_sext<16,15>(trunc_ln708_795_fu_444_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_786_fu_466_p1() {
    sext_ln708_786_fu_466_p1 = esl_sext<16,14>(trunc_ln708_796_fu_457_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_787_fu_479_p1() {
    sext_ln708_787_fu_479_p1 = esl_sext<16,15>(trunc_ln708_797_fu_470_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_788_fu_527_p1() {
    sext_ln708_788_fu_527_p1 = esl_sext<16,15>(trunc_ln708_798_fu_518_p4.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sext_ln708_fu_573_p1() {
    sext_ln708_fu_573_p1 = esl_sext<16,15>(trunc_ln_reg_730.read());
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln1118_348_fu_335_p1() {
    shl_ln1118_348_fu_335_p1 = data_7_V_read.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln1118_348_fu_335_p3() {
    shl_ln1118_348_fu_335_p3 = esl_concat<16,9>(shl_ln1118_348_fu_335_p1.read(), ap_const_lv9_0);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln1118_349_fu_347_p1() {
    shl_ln1118_349_fu_347_p1 = data_7_V_read.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln1118_349_fu_347_p3() {
    shl_ln1118_349_fu_347_p3 = esl_concat<16,5>(shl_ln1118_349_fu_347_p1.read(), ap_const_lv5_0);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln1118_s_fu_200_p1() {
    shl_ln1118_s_fu_200_p1 = data_2_V_read.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln1118_s_fu_200_p3() {
    shl_ln1118_s_fu_200_p3 = esl_concat<16,1>(shl_ln1118_s_fu_200_p1.read(), ap_const_lv1_0);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln_fu_188_p1() {
    shl_ln_fu_188_p1 = data_2_V_read.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_shl_ln_fu_188_p3() {
    shl_ln_fu_188_p3 = esl_concat<16,5>(shl_ln_fu_188_p1.read(), ap_const_lv5_0);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sub_ln1118_268_fu_311_p2() {
    sub_ln1118_268_fu_311_p2 = (!sext_ln1118_863_fu_295_p1.read().is_01() || !sext_ln1118_868_fu_307_p1.read().is_01())? sc_lv<20>(): (sc_bigint<20>(sext_ln1118_863_fu_295_p1.read()) - sc_bigint<20>(sext_ln1118_868_fu_307_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_sub_ln1118_fu_359_p2() {
    sub_ln1118_fu_359_p2 = (!sext_ln1118_865_fu_343_p1.read().is_01() || !sext_ln1118_866_fu_355_p1.read().is_01())? sc_lv<26>(): (sc_bigint<26>(sext_ln1118_865_fu_343_p1.read()) - sc_bigint<26>(sext_ln1118_866_fu_355_p1.read()));
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_tmp_497_fu_218_p4() {
    tmp_497_fu_218_p4 = add_ln1118_fu_212_p2.read().range(21, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_tmp_498_fu_240_p4() {
    tmp_498_fu_240_p4 = mul_ln1118_982_fu_639_p2.read().range(22, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_tmp_499_fu_261_p4() {
    tmp_499_fu_261_p4 = mul_ln1118_983_fu_646_p2.read().range(23, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_tmp_500_fu_483_p4() {
    tmp_500_fu_483_p4 = mul_ln1118_991_fu_702_p2.read().range(23, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_tmp_501_fu_496_p4() {
    tmp_501_fu_496_p4 = mul_ln1118_992_fu_709_p2.read().range(23, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_tmp_fu_299_p1() {
    tmp_fu_299_p1 = data_6_V_read.read();
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_tmp_fu_299_p3() {
    tmp_fu_299_p3 = esl_concat<16,3>(tmp_fu_299_p1.read(), ap_const_lv3_0);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_16_fu_509_p4() {
    trunc_ln708_16_fu_509_p4 = mul_ln1118_993_fu_716_p2.read().range(25, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_5_fu_282_p4() {
    trunc_ln708_5_fu_282_p4 = mul_ln1118_984_fu_653_p2.read().range(25, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_793_fu_379_p4() {
    trunc_ln708_793_fu_379_p4 = mul_ln1118_985_fu_660_p2.read().range(24, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_794_fu_431_p4() {
    trunc_ln708_794_fu_431_p4 = mul_ln1118_987_fu_674_p2.read().range(24, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_795_fu_444_p4() {
    trunc_ln708_795_fu_444_p4 = mul_ln1118_988_fu_681_p2.read().range(24, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_796_fu_457_p4() {
    trunc_ln708_796_fu_457_p4 = mul_ln1118_989_fu_688_p2.read().range(23, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_797_fu_470_p4() {
    trunc_ln708_797_fu_470_p4 = mul_ln1118_990_fu_695_p2.read().range(24, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_798_fu_518_p4() {
    trunc_ln708_798_fu_518_p4 = mul_ln1118_994_fu_723_p2.read().range(24, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_7_fu_365_p4() {
    trunc_ln708_7_fu_365_p4 = sub_ln1118_fu_359_p2.read().range(25, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_9_fu_422_p4() {
    trunc_ln708_9_fu_422_p4 = mul_ln1118_986_fu_667_p2.read().range(25, 10);
}

void dense_resource_ap_fixed_ap_fixed_config2_mult_s::thread_trunc_ln708_s_fu_317_p4() {
    trunc_ln708_s_fu_317_p4 = sub_ln1118_268_fu_311_p2.read().range(19, 10);
}

}

